### ISSUE TITLE
Not very popular on GitHub?

### ISSUE THREAD

**Issue by dandv** [ODataOrg/tutorials#1]
Landed here from the 2nd slide at http://www.odata.org/, but is this the right GitHub org? I see very little forks and stars in these 4 repos at https://github.com/ODataOrg

Maybe link to https://github.com/OData/ in the repo description, and [publicize the membership of developers to the org](https://github.com/webix-hub/tracker/issues/176), so it doesn't look like a forgotten project? (the "People" section is empty at both orgs).

**Comment by liqian19891011** [comment]
@dandv  First of all, this repo ODataOrg is for contents on www.odata.org and https://github.com/OData/ is for various libraries of OData. And the reason that the repo has very few forks and starts is that we just start working on it so they are "new" project instead of a "forgotten project" but we do think you suggestion make sense. We will improve this.
